/**
 * Entity identity and lifecycle helpers.
 *
 * EntityBase is the canonical shape for all hub-domain entities.
 * generateDeterministicId is the single authoritative ID generator — it
 * uses the platform crypto API so every call site produces a UUID v4 without
 * relying on Math.random.
 */

/**
 * Canonical identity + lifecycle fields shared by all hub-domain entities.
 */
export interface EntityBase {
  id: string;
  createdAt: number; // Unix ms
  deletedAt: number | null; // soft-delete; null = live
}

/**
 * Generate a UUID v4 via the platform's `crypto.randomUUID`.
 *
 * The name reflects the call-site contract — "the ID is generated by the
 * platform, not user-provided" — rather than implying the bytes are
 * byte-for-byte reproducible (UUID v4 is random).
 *
 * Throws if `crypto.randomUUID` is unavailable. Modern browsers
 * (Chrome 92+, Firefox 95+, Safari 15.4+) and Node >= 19 provide this;
 * hitting the throw means you are on an unsupported runtime.
 */
export function generateDeterministicId(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  throw new Error('crypto.randomUUID unavailable; cannot generate deterministic ID');
}
