export { default as IPDetailPage } from './IPDetailPage';
export type { IPDetailPageProps } from './IPDetailPage';
export type { StageName } from './IPDetailStageTabs';
export type { IPDetailMode } from './IPDetailModeToggle';
export type { StageState, StageStateMap, StageStateInputs } from './stageState';
export { deriveStageState } from './stageState';
export type { CauseRow, CauseStatus, CauseProjectionInputs } from './stages/causeProjection';
export { projectCauses } from './stages/causeProjection';
export type { ControlClosureInputs } from './stages/ControlOverview';
export type { ProjectOverviewSignals, ProjectOverviewSignalInputs } from './projectOverviewSignals';
export { deriveProjectOverviewSignals } from './projectOverviewSignals';
