import { describe, it, expect, expectTypeOf } from 'vitest';
import { createNewIP } from '../factories';
import type { ImprovementProject } from '../types';

const baseInput = {
  hubId: 'hub-1',
  title: 'Yield drop on heads 5-8',
  currentUserId: 'alice@contoso.com',
  now: () => 12345,
  id: 'fixed-id',
};

describe('createNewIP', () => {
  it('produces a default-shaped IP with the exact expected fields', () => {
    const ip = createNewIP(baseInput);
    expect(ip).toEqual({
      id: 'fixed-id',
      hubId: 'hub-1',
      status: 'active',
      metadata: {
        title: 'Yield drop on heads 5-8',
        members: [
          {
            id: 'fixed-id-lead',
            createdAt: 12345,
            deletedAt: null,
            userId: 'alice@contoso.com',
            displayName: 'alice@contoso.com',
            role: 'lead',
            invitedAt: 12345,
            acceptedAt: 12345,
          },
        ],
      },
      goal: {
        outcomeGoals: [],
      },
      sections: {
        background: {},
        investigationLineage: {},
        approach: {},
        outcomeReference: {},
      },
      issueStatement: undefined,
      createdAt: 12345,
      updatedAt: 12345,
      deletedAt: null,
    });
  });

  it('passes through issueStatement when provided', () => {
    const ip = createNewIP({ ...baseInput, issueStatement: 'yields are dropping' });
    expect(ip.issueStatement).toBe('yields are dropping');
  });

  it('leaves issueStatement undefined when omitted (not empty string)', () => {
    const ip = createNewIP(baseInput);
    expect(ip.issueStatement).toBeUndefined();
    expect('issueStatement' in ip).toBe(true); // explicitly present-but-undefined
  });

  it('honors the status override', () => {
    const draft = createNewIP({ ...baseInput, status: 'draft' });
    const closed = createNewIP({ ...baseInput, status: 'closed' });
    expect(draft.status).toBe('draft');
    expect(closed.status).toBe('closed');
  });

  it("defaults status to 'active' (E1 wedge V1 lifecycle decision)", () => {
    const ip = createNewIP(baseInput);
    expect(ip.status).toBe('active');
  });

  it('preserves the title verbatim (factory does NOT trim — modal handles trimming)', () => {
    const ip = createNewIP({ ...baseInput, title: '  Hello  ' });
    expect(ip.metadata.title).toBe('  Hello  ');
  });

  it('populates the Lead member with userId + displayName fallback', () => {
    const ip = createNewIP(baseInput);
    expect(ip.metadata.members).toHaveLength(1);
    expect(ip.metadata.members![0]).toMatchObject({
      userId: 'alice@contoso.com',
      displayName: 'alice@contoso.com', // falls back to userId when no display name supplied
      role: 'lead',
    });
  });

  it('uses currentUserDisplayName for the Lead member when supplied', () => {
    const ip = createNewIP({ ...baseInput, currentUserDisplayName: 'Alice Chen' });
    expect(ip.metadata.members![0].displayName).toBe('Alice Chen');
    expect(ip.metadata.members![0].userId).toBe('alice@contoso.com');
  });

  it('uses generateDeterministicId() for the IP id when not supplied', () => {
    const ip = createNewIP({
      hubId: 'hub-1',
      title: 'Auto-id project',
      currentUserId: 'alice@contoso.com',
    });
    // UUID v4 shape: 8-4-4-4-12 hex, with version nibble '4'
    expect(ip.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
  });

  it('uses generateDeterministicId() for the Lead member id when no IP id is supplied', () => {
    const ip = createNewIP({
      hubId: 'hub-1',
      title: 'Auto-id project',
      currentUserId: 'alice@contoso.com',
    });
    // The member id is also a fresh UUID (not derived from the IP id when both autogenerated)
    expect(ip.metadata.members![0].id).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/
    );
    expect(ip.metadata.members![0].id).not.toBe(ip.id);
  });

  it('uses Date.now() for timestamps when no clock is supplied', () => {
    const before = Date.now();
    const ip = createNewIP({
      hubId: 'hub-1',
      title: 'Default-clock project',
      currentUserId: 'alice@contoso.com',
    });
    const after = Date.now();
    expect(ip.createdAt).toBeGreaterThanOrEqual(before);
    expect(ip.createdAt).toBeLessThanOrEqual(after);
    expect(ip.updatedAt).toBe(ip.createdAt);
  });

  it('returns a value assignable to ImprovementProject (compile-time check)', () => {
    const ip = createNewIP(baseInput);
    expectTypeOf(ip).toMatchTypeOf<ImprovementProject>();
  });

  it('sections are independent empty objects (not shared references)', () => {
    const a = createNewIP(baseInput);
    const b = createNewIP({ ...baseInput, id: 'other-id' });
    expect(a.sections.background).not.toBe(b.sections.background);
    expect(a.sections.investigationLineage).not.toBe(b.sections.investigationLineage);
    expect(a.sections.approach).not.toBe(b.sections.approach);
    expect(a.sections.outcomeReference).not.toBe(b.sections.outcomeReference);
  });

  it('outcomeGoals is a fresh empty array per call (no shared mutable default)', () => {
    const a = createNewIP(baseInput);
    const b = createNewIP({ ...baseInput, id: 'other-id' });
    expect(a.goal.outcomeGoals).not.toBe(b.goal.outcomeGoals);
    expect(a.goal.outcomeGoals).toEqual([]);
  });
});
